# Generated by Django 5.1.5 on 2025-02-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.TextField(max_length=255)),
                ('CNPJ', models.IntegerField()),
            ],
        ),
    ]
