# Generated by Django 5.1.5 on 2025-02-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=255)),
                ('whatsapp', models.TextField(max_length=12)),
                ('cnpj', models.TextField(max_length=12)),
                ('desc', models.TextField(max_length=255)),
            ],
        ),
    ]
